<?php

namespace App\Controller;

use App\Controller\AppController;
use App\Model\Table\UsersTable;
use App\Policy\LocatorsPolicy;
use Cake\Auth\DefaultPasswordHasher;
use Cake\Event\Event;

/**
 * Locators Controller
 *
 * @property \App\Model\Table\LocatorsTable $Locators
 * @property \App\Model\Table\UsersTable $Users
 *
 * @method \App\Model\Entity\Locator[] paginate($object = null, array $settings = [])
 */
class LocatorsController extends AppController
{

    function isAuthorized($user)
    {
        $element = $this->Users->findById($this->request->getParam('pass.0'))
            ->first();

        return LocatorsPolicy::isAuthorized($this->request->action, $user, $element);
    }

    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub

        $this->viewBuilder()->setHelpers(['Users']);
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->loadModel('Users');
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $locators = $this->Users->find()
            ->where(['role' => UsersTable::ROLE_LOCATOR]);

        $this->set(compact('locators'));
        $this->set('_serialize', ['locators']);
    }

    /**
     * View method
     *
     * @param string|null $id Locator id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $locator = $this->Locators->get($id, [
            'contain' => ['Users']
        ]);

        $this->set('locator', $locator);
        $this->set('_serialize', ['locator']);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $locator = $this->Locators->newEntity();
        if ($this->request->is('post')) {
            $locator = $this->Locators->patchEntity($locator, $this->request->getData());
            if ($this->Locators->save($locator)) {
                $this->Flash->success(__('The locator has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The locator could not be saved. Please, try again.'));
        }
        $users = $this->Locators->Users->find('list', ['limit' => 200]);
        $this->set(compact('locator', 'users'));
        $this->set('_serialize', ['locator']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Locator id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $locator = $this->Locators->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $locator = $this->Locators->patchEntity($locator, $this->request->getData());
            if ($this->Locators->save($locator)) {
                $this->Flash->success(__('The locator has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The locator could not be saved. Please, try again.'));
        }
        $users = $this->Locators->Users->find('list', ['limit' => 200]);
        $this->set(compact('locator', 'users'));
        $this->set('_serialize', ['locator']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Locator id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod('delete');

        $locator = $this->Users->get($id);

        if ($this->Users->delete($locator)) {
            $this->Flash->success(__('Locador excluído'));
        } else {
            $this->Flash->error(__('Erro ao excluir Locador'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function form($id = null)
    {
        $this->set(compact('id'));

        if ($id) {
            $user = $this->Users->get($id, [
                'contain' => ['Locators']
            ]);
        } else {
            $user = $this->Users->newEntity();
        }

        if ($this->request->is(['post', 'put'])) {
            $user = $this->Users->patchEntity($user, $this->request->getData());

            $user['role'] = UsersTable::ROLE_LOCATOR;

            if (!$id) {
                $user['username'] = $this->Users->getLastUsername() + 1;
                $user['password'] = $this->Users->generatePassword();
                $user['locator']['password'] = $user['password'];
            } else {
                $user['password'] = (new DefaultPasswordHasher)->hash($user['locator']['password']);
            }

            if ($this->Users->save($user)) {
                $this->Flash->success('Salvo com sucesso');

                return $this->redirect(['action' => 'index']);
            } else {
                $this->Flash->error('Existem erros no formulário, favor verificar');
            }
        }

        $this->set(compact('user'));
    }

    public function fetch()
    {
        $this->autoRender = false;
        $this->response->type('json');

        $search = $this->Users->parseSearch($this->Users->parseUsername($this->request->getQuery('name')));

        $locators = $this->Users->find()
            ->contain('Locators')
            ->where(['role' => UsersTable::ROLE_LOCATOR])
            ->where([
                "OR" => [
                    "Users.nome LIKE" => $search,
                    "Users.username LIKE" => $search,
                ],
            ])
            ->limit(10);

//        $this->set(compact("locators"));
//        $this->set('_serialize', ['locators']);

        $this->response->body(json_encode($locators));
    }
}
