<?php

namespace App\Controller;

use App\Controller\AppController;
use App\Model\Table\PropertiesCompositionsTable;
use App\Model\Table\PropertiesTable;
use App\Model\Table\UsersTable;
use App\Policy\PropertiesPolicy;
use App\View\Helper\GlobalCombosHelper;
use Cake\Event\Event;

/**
 * Properties Controller
 *
 * @property \App\Model\Table\PropertiesTable $Properties
 * @property \App\Model\Table\PropertiesCompositionsTable $PropertiesCompositions
 * @property \App\Model\Table\PropertiesFeesTable $PropertiesFees
 * @property \App\Model\Table\PropertiesPricesTable $PropertiesPrices
 * @property \App\Model\Table\LocatorsAssociationsTable $LocatorsAssociations
 * @property \App\Model\Table\UsersTable $Users
 * @property \App\Model\Table\CommonBillsTable $CommonBills
 *
 * @method \App\Model\Entity\Property[] paginate($object = null, array $settings = [])
 */
class PropertiesController extends AppController
{

    function isAuthorized($user)
    {
//        $element = $this->Users->findById($this->request->getParam('pass.0'))
//            ->first();

        return PropertiesPolicy::isAuthorized($this->request->action, $user);
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->loadComponent('GoogleMaps');
        $this->loadComponent('Formatter');
        $this->loadComponent('GraphUtil');

        $this->loadModel('PropertiesCompositions');
        $this->loadModel('PropertiesFees');
        $this->loadModel('PropertiesPrices');
        $this->loadModel('LocatorsAssociations');
        $this->loadModel('Users');
        $this->loadModel('CommonBills');
    }

    public function beforeRender(Event $event)
    {
        parent::beforeRender($event); // TODO: Change the autogenerated stub

        $this->viewBuilder()->setHelpers(['Properties', 'Pagination']);
    }

    /**
     * Index method
     *
     * @return \Cake\Http\Response|void
     */
    public function index()
    {
        $this->paginate = [
            'order' => ['id' => 'desc'],
            'contain' => ['Locators.Users', 'PropertiesPhotos'],
            'limit' => 8,
        ];
        $properties = $this->paginate($this->Properties);

        $markers = [];
        foreach ($properties as $p) {
            $markers[] = [
                'latitude' => $p['latitude'],
                'longitude' => $p['longitude'],
                'photo' => $p['main_photo'],
                'address' => $p['full_address'],
                'property_id' => $p['id'],
                'property_code' => $p['formatted_code'],
            ];
        }

        $this->set(compact('properties', 'markers'));
    }

    /**
     * View method
     *
     * @param string|null $id Property id.
     * @return \Cake\Http\Response|void
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $property = $this->Properties->get($id, [
            'contain' => [
                'Users',
                'Locators.Users',
                'PropertiesCompositions',
                'PropertiesFees',
                'PropertiesPrices',
            ]
        ]);

        $locatorsAssociationsDataset = [];

        $associations = $this->LocatorsAssociations->find()
            ->contain('Associateds.Users')
            ->where(['locator_1' => $property['locator_id']])
            ->where(['property_id' => $property['id']]);

        $ownerPercentage = 100;
        $sum = 0;

        $locatorsColors = [];

        foreach ($associations as $a) {
            $locatorsAssociationsDataset['labels'][] = sprintf('%s - %s', $a['associated']['user']['formatted_username'], $a['associated']['user']['nome']);
            $locatorsAssociationsDataset['dataset'][] = $a['porcentagem'];

            $locatorsColors[$a['locator_2']] = $this->GraphUtil->getRandomColor();

            $locatorsAssociationsDataset['colors'][] = $locatorsColors[$a['locator_2']];

            $sum += $a['porcentagem'];
        }

        $locatorsAssociationsDataset['labels'][] = sprintf('%s - %s', $property['locator']['user']['formatted_username'], $property['locator']['user']['nome']);
        $locatorsAssociationsDataset['dataset'][] = $ownerPercentage - $sum;

        $locatorsColors[$property['locator_id']] = $this->GraphUtil->getRandomColor();

        $locatorsAssociationsDataset['colors'][] = $locatorsColors[$property['locator_id']];

        $this->set(compact('locatorsAssociationsDataset'));

        $commonBillsArray = [];

        foreach (PropertiesTable::$propertiesBills as $key => $b) {
            if (!empty($property['properties_fees'][0][$key])) {
                $commonBills = $this->CommonBills->find()
                    ->contain('Properties.Locators.Users')
                    ->where(['CommonBills.tipo' => $key])
                    ->where(['property_1' => $id]);

                if (!$commonBills->isEmpty()) {
                    $commonBillsArray[$key] = $commonBills;
                }
            }
        }

        $this->set('commonBills', $commonBillsArray);

        $this->set('property', $property);
        $this->set('_serialize', ['property']);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $property = $this->Properties->newEntity();
        if ($this->request->is('post')) {
            $property = $this->Properties->patchEntity($property, $this->request->getData());
            if ($this->Properties->save($property)) {
                $this->Flash->success(__('The property has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The property could not be saved. Please, try again.'));
        }
        $locators = $this->Properties->Locators->find('list', ['limit' => 200]);
        $this->set(compact('property', 'locators'));
        $this->set('_serialize', ['property']);
    }

    /**
     * Edit method
     *
     * @param string|null $id Property id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Network\Exception\NotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $property = $this->Properties->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
            $property = $this->Properties->patchEntity($property, $this->request->getData());
            if ($this->Properties->save($property)) {
                $this->Flash->success(__('The property has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The property could not be saved. Please, try again.'));
        }
        $locators = $this->Properties->Locators->find('list', ['limit' => 200]);
        $this->set(compact('property', 'locators'));
        $this->set('_serialize', ['property']);
    }

    /**
     * Delete method
     *
     * @param string|null $id Property id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod('delete');

        $property = $this->Properties->get($id);
        if ($this->Properties->delete($property)) {
            $this->Flash->success(__('Excluído com sucesso'));
        } else {
            $this->Flash->error(__('The property could not be deleted. Please, try again.'));
        }

        return $this->redirect(['action' => 'index']);
    }

    public function form($id = null)
    {
        if (!$id) {
            $property = $this->Properties->newEntity();
        } else {
            $property = $this->Properties->get($id, [
                'contain' => [
                    'Users',
                    'Locators.Users',
                    'PropertiesCompositions',
                    'PropertiesFees',
                    'PropertiesPrices',
                ]
            ]);
        }

        if ($this->request->is('get')) {
            if (!empty($property['properties_compositions'][0])) {
                foreach (PropertiesCompositionsTable::$propertiesItems as $i) {
                    $property[$i->getKey()] = $property['properties_compositions'][0][$i->getKey()];
                }

                foreach (PropertiesCompositionsTable::$compositions as $key => $c) {
                    $property[$key] = $property['properties_compositions'][0][$key];
                }
            }

            if (!empty($property['properties_prices'][0])) {
                $property['valor'] = $this->Formatter->formatDecimal($property['properties_prices'][0]['valor']);
            }

            if (!empty($property['properties_fees'][0])) {
                $property['taxa_administrativa'] = $this->Formatter->formatDecimal($property['properties_fees'][0]['taxa_administrativa']);
                $property['taxa_administrativa_tipo'] = $property['properties_fees'][0]['taxa_administrativa_tipo'];
                $property['taxa_administrativa_incidencia'] = $property['properties_fees'][0]['taxa_administrativa_incidencia'];
                $property['parcelas_13_taxa_administrativa'] = $property['properties_fees'][0]['parcelas_13_taxa_administrativa'];

                foreach (PropertiesTable::$propertiesBills as $key => $b) {
                    $property[$key] = $property['properties_fees'][0][$key];
                }
            }

            if (!empty($property['locator'])) {
                $property['locator_search'] = sprintf('%s - %s', $property['locator']['user']['nome'], $property['locator']['user']['formatted_username']);
            }

            if (!empty($property['user'])) {
                $property['broker_search'] = sprintf('%s - %s', $property['user']['nome'], $property['user']['formatted_username']);
            }
        }

        if ($this->request->is(['post', 'put'])) {
            $this->Properties->patchEntity($property, $this->request->getData());

            $geoInfo = $this->GoogleMaps->getGeoInfo(implode(' ', array_filter([
                $property['endereco'],
                $property['numero'],
                $property['complemento'],
                $property['bairro'],
                $property['cidade'],
                $property['uf'],
                $property['cep'],
            ])));

            $property['latitude'] = $geoInfo['latitude'];
            $property['longitude'] = $geoInfo['longitude'];

            if ($this->Properties->save($property)) {
                $propertyComposition = $this->PropertiesCompositions->newEntity();

                foreach (PropertiesCompositionsTable::$propertiesItems as $i) {
                    $propertyComposition[$i->getKey()] = $property[$i->getKey()];
                }

                foreach (PropertiesCompositionsTable::$compositions as $key => $c) {
                    $propertyComposition[$key] = $property[$key];
                }

                $propertyComposition['start_date'] = date('Y-m-d');
                $propertyComposition['property_id'] = $property['id'];

                if ($this->PropertiesCompositions->save($propertyComposition)) {
                    $propertyFees = $this->PropertiesFees->newEntity();

                    $propertyFees['taxa_administrativa'] = $this->Properties->parseDecimal($property['taxa_administrativa']);
                    $propertyFees['taxa_administrativa_tipo'] = GlobalCombosHelper::COMISSION_TYPE_PERCENTAGE;
                    $propertyFees['taxa_administrativa_incidencia'] = $property['taxa_administrativa_incidencia'];
                    $propertyFees['parcelas_13_taxa_administrativa'] = $property['parcelas_13_taxa_administrativa'];

                    foreach (PropertiesTable::$propertiesBills as $key => $b) {
                        if ($property[$key] == true) {
                            $propertyFees[$key] = $property["salary_$key"];
                        } else {
                            $propertyFees[$key] = null;
                        }
                    }

                    $propertyFees['start_date'] = date('Y-m-d');
                    $propertyFees['property_id'] = $property['id'];

                    if ($this->PropertiesFees->save($propertyFees)) {
                        $propertyPrice = $this->PropertiesPrices->newEntity();

                        $propertyPrice['valor'] = $this->Properties->parseDecimal($property['valor']);
                        $propertyPrice['start_date'] = date('Y-m-d');
                        $propertyPrice['property_id'] = $property['id'];

                        if ($this->PropertiesPrices->save($propertyPrice)) {
                            $this->Flash->success('Salvo com sucesso');

                            $this->redirect(['action' => 'view', $property['id']]);
                        }
                    }
                }
            }
        }

        $this->set(compact('property'));
    }

    public function fetch()
    {
        $this->autoRender = false;
        $this->response->type('json');

        $search = $this->Properties->parseSearch($this->Properties->parseCode($this->request->getQuery('name')));

        $properties = $this->Properties->find()
            ->contain('Locators.Users')
            ->where([
                "OR" => [
                    "Properties.id LIKE" => $search,
                    "Properties.endereco LIKE" => $search,
                    "Properties.numero LIKE" => $search,
                    "Properties.complemento LIKE" => $search,
                    "Properties.bairro LIKE" => $search,
                    "Properties.cidade LIKE" => $search,
                    "Properties.uf LIKE" => $search,
                ],
            ])
            ->limit(10);

        $this->response->body(json_encode($properties));
    }

    public function fetchBroker()
    {
        $this->autoRender = false;
        $this->response->type('json');

        $search = $this->Users->parseSearch($this->Users->parseUsername($this->request->getQuery('name')));

        $brokers = $this->Users->find()
            ->where(['or' => [
                ['role' => UsersTable::ROLE_BROKER],
                ['role' => UsersTable::ROLE_ADMIN],
            ]])
            ->where([
                "OR" => [
                    "Users.nome LIKE" => $search,
                    "Users.username LIKE" => $search,
                ],
            ])
            ->limit(10);

//        $this->set(compact("locators"));
//        $this->set('_serialize', ['locators']);

        $this->response->body(json_encode($brokers));
    }

    public function updateLatitudeLongitude()
    {
        $property = $this->Properties->get($this->request->getData('id'));

        $property['latitude'] = $this->request->getData('latitude');
        $property['longitude'] = $this->request->getData('longitude');

        $this->Properties->save($property);

        $this->autoRender = false;
    }
}
