<?php

namespace App\View\Helper;

use Cake\ORM\TableRegistry;
use Cake\View\Helper;
use Cake\View\View;

/**
 * CompanyData helper
 */
class CompanyDataHelper extends Helper
{

    /**
     * Default configuration.
     *
     * @var array
     */
    protected $_defaultConfig = [];

    private $companyData;

    public function initialize(array $config)
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

        $this->companyData = TableRegistry::get('CompanyData')->find()->first();
    }

    public function getAppTitle()
    {
        return ($this->companyData) ? $this->companyData['nome'] : 'Sistema de Imobiliária';
    }

    public function getAppLogo()
    {
        $fileName = sprintf('%s/file/logo.png', WWW_ROOT);

        if (file_exists($fileName)) {
            return $fileName;
        } else {
            return 'new_logo_kdym.png';
        }
    }

    public function getAppSmallLogo()
    {
        $fileName = sprintf('%s/file/small_logo.png', WWW_ROOT);

        if (file_exists($fileName)) {
            return $fileName;
        } else {
            return 'kdym_small.png';
        }
    }

}
